from datetime import datetime
from config import db, ma
from marshmallow import Schema, fields, validate
#from models.media import Media
#from models.brand import Brand
from models.property import Property
from common.base_audit import BaseAudit

class MediaBanners(db.Model, BaseAudit):
    __tablename__="def_media_banners"

    iddef_media_banners = db.Column(db.Integer, primary_key=True)
    ids_media = db.Column(db.JSON, nullable=False, default ="[]") #category = desktop,mobile,trade,letter => [{"iddef_media":0,"category":"desktop"}]
    type_banner = db.Column(db.Integer, default = 1, nullable=False)
    name = db.Column(db.String(100), nullable=False, default="")
    property_codes = db.Column(db.JSON, nullable=False, default ="[]")
    lang_option = db.Column(db.Integer, default = 0, nullable=False)
    lang_codes = db.Column(db.JSON, nullable=False, default ="[]")
    market_option = db.Column(db.Integer, default = 0, nullable=False)
    marketing = db.Column(db.JSON, nullable=False, default ="[]")
    booking_window_option = db.Column(db.Integer, default = 0, nullable=False)
    booking_window = db.Column(db.JSON, nullable=False, default ="[]")
    brand_option = db.Column(db.Integer, default = 0, nullable=False)
    brand_codes = db.Column(db.JSON, nullable=False, default ="[]")
    geo_targeting_option = db.Column(db.Integer, default = 0, nullable=False)
    geo_targeting_countries = db.Column(db.JSON, nullable=False, default ="[]")
    pages = db.Column(db.JSON, nullable=False, default ="[]")
    order = db.Column(db.Integer, default= 1,nullable=False)
    estado = db.Column(db.Integer,nullable=False)
    usuario_creacion = db.Column(db.String(45), nullable=False, default="")
    fecha_creacion = db.Column(db.DateTime, default=datetime.utcnow)
    usuario_ultima_modificacion = db.Column(db.String(45), default="")
    fecha_ultima_modificacion = db.Column(db.DateTime, default="1900-01-01 00:00:00", onupdate=datetime.utcnow)

class MediaBannersSchema(ma.Schema):
    iddef_media_banners = fields.Integer()
    ids_media = fields.List(fields.Dict(),required=True)
    data_media = fields.List(fields.Dict())
    type_banner = fields.Integer(required=True)
    name = fields.String(required=True,validate=validate.Length(max=100))
    property_codes = fields.List(fields.String(),required=True)
    lang_option = fields.Integer(required=True)
    lang_codes = fields.List(fields.String(),required=True)
    market_option = fields.Integer(required=True)
    marketing = fields.List(fields.Integer(),required=True)
    booking_window_option = fields.Integer(required=True)
    booking_window = fields.List(fields.Dict(),required=True)
    brand_option = fields.Integer(required=True)
    brand_codes = fields.List(fields.String(),required=True)
    geo_targeting_option = fields.Integer(required=True)
    geo_targeting_countries = fields.List(fields.Integer(),required=True)
    pages = fields.List(fields.String(),required=True)
    order = fields.Integer(required=True)
    estado = fields.Integer(required=True)
    usuario_creacion = fields.String(required=True, validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(required=True, validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")

class MediaBannersUpdateSchema(ma.Schema):
    iddef_media_banners = fields.Integer(required=True)
    ids_media = fields.List(fields.Dict(),required=True)
    data_media = fields.List(fields.Dict())
    type_banner = fields.Integer(required=True)
    name = fields.String(required=True,validate=validate.Length(max=100))
    property_codes = fields.List(fields.String(),required=True)
    lang_option = fields.Integer(required=True)
    lang_codes = fields.List(fields.String(),required=True)
    market_option = fields.Integer(required=True)
    marketing = fields.List(fields.Integer(),required=True)
    booking_window_option = fields.Integer(required=True)
    booking_window = fields.List(fields.Dict(),required=True)
    brand_option = fields.Integer(required=True)
    brand_codes = fields.List(fields.String(),required=True)
    geo_targeting_option = fields.Integer(required=True)
    geo_targeting_countries = fields.List(fields.Integer(),required=True)
    pages = fields.List(fields.String(),required=True)
    order = fields.Integer(required=True)
    estado = fields.Integer(required=True)
    usuario_creacion = fields.String(validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(required=True, validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")

class MediaBannersGetSchema(ma.Schema):
    iddef_media_banners = fields.Integer()
    ids_media = fields.List(fields.Dict())
    data_media = fields.List(fields.Dict()) #[{"iddef_media":0,"category":"desktop","media_name":"","url":""}]
    type_banner = fields.Integer()
    name = fields.String(validate=validate.Length(max=100))
    property_codes = fields.List(fields.String())
    lang_option = fields.Integer()
    lang_codes = fields.List(fields.String())
    market_option = fields.Integer()
    marketing = fields.List(fields.Integer()) 
    booking_window_option = fields.Integer()
    booking_window = fields.List(fields.Dict())
    brand_option = fields.Integer()
    brand_codes = fields.List(fields.String())
    geo_targeting_option = fields.Integer()
    geo_targeting_countries = fields.List(fields.Integer())
    pages = fields.List(fields.String())
    media_name = fields.String()
    order = fields.Integer()
    estado = fields.Integer()
    usuario_creacion = fields.String(validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")

