from config import db, ma
from marshmallow import Schema, fields, validate
from datetime import datetime
from .policy_guarantee_deposit import PolicyGuaranteeDeposit, PolicyGuaranteeDepositSchema
from .policy_guarantee_antifraud import PolicyGuaranteeAntifraud, PolicyGuaranteeAntifraudSchema, DefaultPolicyGuaranteeAntifraudSchema
from common.util import Util

class PolicyGuarantee(db.Model):
    __tablename__ = "def_policy_guarantee"

    iddef_policy_guarantee = db.Column(db.Integer, primary_key=True)
    iddef_policy = db.Column(db.Integer, db.ForeignKey("def_policy.iddef_policy"), nullable=False)
    iddef_policy_guarantee_type = db.Column(db.Integer, db.ForeignKey("def_policy_guarantee_type.iddef_policy_guarantee_type"), nullable=False)
    policy_guarantee_deposits = db.relationship('PolicyGuaranteeDeposit', backref=db.backref('def_policy_guarantee', lazy=True))
    nights_applied_antifraud = db.Column(db.Integer, nullable=False, default=0)
    policy_guarantee_antifrauds = db.relationship('PolicyGuaranteeAntifraud', backref=db.backref('def_policy_guarantee', lazy="select"))
    allow_hold_free = db.Column(db.Integer, nullable=False, default=0)
    hold_duration = db.Column(db.Integer, nullable=False, default=0)
    stay_dates_option = db.Column(db.Integer, nullable=False, default=0)    
    stay_dates = db.Column(db.JSON)
    reminder_lead_time = db.Column(db.Integer, nullable=False, default=0)
    offer_last_chance_promotion = db.Column(db.Integer, nullable=False, default=0)
    discount_per_night = db.Column(db.Numeric(15,4), nullable=False, default=0)
    type_discount = db.Column(db.Integer, nullable=False,default=0)
    min_lead_time = db.Column(db.Integer, nullable=False,default=0)
    availability_threshold = db.Column(db.Integer, nullable=False, default=0)
    description_en = db.Column(db.Text(), nullable=False)
    description_es = db.Column(db.Text(), nullable=False)
    estado = db.Column(db.Integer,nullable=False)
    usuario_creacion = db.Column(db.String(45), nullable=False)
    fecha_creacion = db.Column(db.DateTime, default=datetime.utcnow)
    usuario_ultima_modificacion = db.Column(db.String(45), default="")
    fecha_ultima_modificacion = db.Column(db.DateTime, default="1900-01-01 00:00:00", onupdate=datetime.utcnow)

class PolicyGuaranteeSchema(ma.Schema):
    iddef_policy_guarantee = fields.Integer()
    iddef_policy = fields.Integer(required=True)
    iddef_policy_guarantee_type = fields.Integer(required=True)
    policy_guarantee_deposits = fields.Nested(PolicyGuaranteeDepositSchema, many=True, exclude=Util.get_default_excludes())
    nights_applied_antifraud = fields.Integer(required=True)
    policy_guarantee_antifrauds = fields.Nested(PolicyGuaranteeAntifraudSchema, many=True, exclude=Util.get_default_excludes())
    allow_hold_free = fields.Integer(required=True)
    hold_duration = fields.Integer(required=True)
    stay_dates_option = fields.Integer(required=True)
    stay_dates = fields.Dict(required=True)
    reminder_lead_time = fields.Integer(required=True)
    offer_last_chance_promotion = fields.Integer(required=True)
    discount_per_night = fields.Decimal(required=True, as_string=True)
    type_discount = fields.Integer(required=True)
    min_lead_time = fields.Integer(required=True)
    availability_threshold = fields.Integer(required=True)
    description_en = fields.String(required=True)
    description_es = fields.String(required=True)
    estado = fields.Integer()
    usuario_creacion = fields.String(validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")

class GetPolicyGuaranteeSchema(ma.Schema):
    iddef_policy_guarantee = fields.Integer()
    iddef_policy = fields.Integer()
    iddef_policy_guarantee_type = fields.Integer()
    policy_guarantee_deposits = fields.Nested(PolicyGuaranteeDepositSchema, many=True, exclude=Util.get_default_excludes())
    allow_hold_free = fields.Integer()
    hold_duration = fields.Integer()
    stay_dates_option = fields.Integer()
    stay_dates = fields.Dict()
    reminder_lead_time = fields.Integer()
    offer_last_chance_promotion = fields.Integer()
    discount_per_night = fields.Decimal(as_string=True)
    type_discount = fields.Integer()
    min_lead_time = fields.Integer()
    availability_threshold = fields.Integer()
    description_en = fields.String()
    description_es = fields.String()
    estado = fields.Integer()
    usuario_creacion = fields.String(validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")

class DefaultPolicyGuaranteeSchema(ma.Schema):
    iddef_policy_guarantee = fields.Integer()
    iddef_policy = fields.Integer(required=True)
    iddef_policy_guarantee_type = fields.Integer(required=True)
    allow_hold_free = fields.Integer(required=True)
    hold_duration = fields.Integer(required=True)
    stay_dates_option = fields.Integer(required=True)
    stay_dates = fields.Dict(required=True)
    reminder_lead_time = fields.Integer(required=True)
    offer_last_chance_promotion = fields.Integer(required=True)
    discount_per_night = fields.Decimal(required=True, as_string=True)
    type_discount = fields.Integer(required=True)
    min_lead_time = fields.Integer(required=True)
    availability_threshold = fields.Integer(required=True)
    description_en = fields.String(required=True)
    description_es = fields.String(required=True)
    nights_applied_antifraud = fields.Integer(required=True)
    policy_guarantee_antifrauds = fields.Nested(DefaultPolicyGuaranteeAntifraudSchema, many=True, exclude=Util.get_default_excludes())
    estado = fields.Integer()
    usuario_creacion = fields.String(validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")

class GetPolicyGuaranteeDefaultSchema(ma.Schema):
    iddef_policy_guarantee = fields.Integer()
    iddef_policy = fields.Integer()
    iddef_policy_guarantee_type = fields.Integer()
    allow_hold_free = fields.Integer()
    hold_duration = fields.Integer()
    stay_dates_option = fields.Integer()
    stay_dates = fields.Dict()
    reminder_lead_time = fields.Integer()
    offer_last_chance_promotion = fields.Integer()
    discount_per_night = fields.Decimal(as_string=True)
    type_discount = fields.Integer()
    min_lead_time = fields.Integer()
    availability_threshold = fields.Integer()
    description_en = fields.String()
    description_es = fields.String()
    nights_applied_antifraud = fields.Integer()
    policy_guarantee_antifrauds = fields.Nested(PolicyGuaranteeAntifraudSchema, many=True, exclude=Util.get_default_excludes())
    estado = fields.Integer()
    usuario_creacion = fields.String(validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")