from datetime import datetime

from config import db, ma
from marshmallow import Schema, fields, validate
from models.promo_code_discount_type import PromoCodeDiscountType
from models.promo_code_type_amount import PromoCodeTypeAmount
from models.promo_code_date import PromoCodeDate, PromoCodeDateSchema
#from models.property import Property
from models.promo_code_rateplan import PromoCodeRatePlan, PromoCodeRatePlanSchema
from models.promo_code_channels import PromoCodeChannels, PromoCodeChannelsSchema
from common.util import Util

class PromoCode(db.Model):
    __tablename__ = "def_promo_code"

    iddef_promo_code = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150), nullable=False)
    code = db.Column(db.String(50), nullable=False)
    #iddef_property = db.Column(db.Integer, db.ForeignKey("def_property.iddef_property"), nullable=False)
    iddef_promo_code_discount_type = db.Column(db.Integer, db.ForeignKey("def_promo_code_discount_type.iddef_promo_code_discount_type"), nullable=False)
    value_discount = db.Column(db.Float, nullable=False)
    iddef_promo_code_type_amount = db.Column(db.Integer, nullable=False)
    #iddef_promo_code_type_amount = db.Column(db.Integer, db.ForeignKey("def_promo_code_type_amount.iddef_promo_code_type_amount"), nullable=False)
    currency_code = db.Column(db.String(15), nullable=False, default= "USD")
    room_types_option = db.Column(db.Integer,nullable=False)
    min_LOS_option = db.Column(db.Integer,nullable=False)
    min_LOS_value = db.Column(db.Float, nullable=False)
    min_booking_amount_option = db.Column(db.Integer,nullable=False)
    min_booking_value = db.Column(db.Float, nullable=False)
    max_booking_amount_option = db.Column(db.Integer,nullable=False)
    max_booking_value = db.Column(db.Float, nullable=False)
    stay_dates_option = db.Column(db.Integer,nullable=False)
    stay_dates = db.Column(db.JSON, nullable=False)
    booking_dates_option = db.Column(db.Integer,nullable=False)
    booking_dates = db.Column(db.JSON, nullable=False)
    booking_times = db.Column(db.JSON, nullable=False)
    global_sales_limit_option = db.Column(db.Integer,nullable=False)
    global_sales_limit_value = db.Column(db.Float, nullable=False)
    cancel_policy_id = db.Column(db.Integer,nullable=False)
    channel_option = db.Column(db.Integer,nullable=False)
    maximum_nights_option = db.Column(db.Integer, nullable=False, default="0")
    maximum_nights_value = db.Column(db.Integer, nullable=False, default="0")
    estado = db.Column(db.Integer,nullable=False)
    usuario_creacion = db.Column(db.String(45), nullable=False, default="")
    fecha_creacion = db.Column(db.DateTime, default=datetime.utcnow)
    usuario_ultima_modificacion = db.Column(db.String(45), default="")
    fecha_ultima_modificacion = db.Column(db.DateTime, default="1900-01-01 00:00:00", onupdate=datetime.utcnow)
    discount_type = db.relationship('PromoCodeDiscountType', backref=db.backref('def_promo_code_discount_type', lazy='dynamic'))
    #type_amount_name = db.relationship('PromoCodeTypeAmount', backref=db.backref('def_promo_code_type_amount', lazy='dynamic'))
    #bookable_until = db.relationship('PromoCodeDate', backref=db.backref('def_promo_code_date', lazy= 'select'))
    promo_code_rateplans = db.relationship('PromoCodeRatePlan', backref=db.backref('promo_code', lazy='joined'))
    
    
    

class PromoCodeSchema(ma.Schema):
    iddef_promo_code = fields.Integer(dump_only=True)
    name = fields.String(required=True,validate=validate.Length(max=150))
    code = fields.String(required=True,validate=validate.Length(max=50))
    #iddef_property = fields.Integer(required=True)
    iddef_promo_code_discount_type = fields.Integer(required=True)
    value_discount = fields.Float(required=True)
    iddef_promo_code_type_amount = fields.Integer(required=True)
    currency_code = fields.String(required=True,validate=validate.Length(max=15))
    room_types_option = fields.Integer(required=True,validate=validate.Length(max=6))
    min_LOS_option = fields.Integer(required=True,validate=validate.Length(max=6))
    min_LOS_value = fields.Float(required=True)
    min_booking_amount_option = fields.Integer(required=True,validate=validate.Length(max=6))
    min_booking_value = fields.Float(required=True)
    max_booking_amount_option = fields.Integer(required=True,validate=validate.Length(max=6))
    max_booking_value = fields.Float(required=True)
    stay_dates_option = fields.Integer(required=True,validate=validate.Length(max=6))
    stay_dates = fields.Dict(required=True)
    booking_dates_option =fields.Integer(required=True,validate=validate.Length(max=6))
    booking_dates = fields.Dict(required=True)
    booking_times = fields.Dict(required=True)
    global_sales_limit_option = fields.Integer(required=True,validate=validate.Length(max=6))
    global_sales_limit_value = fields.Float(required=True)
    cancel_policy_id = fields.Integer(required=True,validate=validate.Length(max=11))
    channel_option = fields.Integer(required=True,validate=validate.Length(max=6))
    maximum_nights_option = fields.Integer(required=True, validate=validate.Length(max=6))
    maximum_nights_value = fields.Integer(required=True, validate=validate.Length(max=10))
    estado = fields.Integer()
    usuario_creacion = fields.String(required=True, validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    discount_type = ma.Pluck("PromoCodeDiscountTypeSchema", 'name')
    #type_amount_name = ma.Pluck("PromoCodeTypeAmountSchema", 'name')
    #bookable_until = ma.Pluck("PromoCodeDateSchema", 'end_date', many=True)
    promo_code_rateplans = fields.Nested(PromoCodeRatePlanSchema(exclude=Util.get_default_excludes()), many=True)
    
       

class PromoCodeRefSchema(ma.Schema):
    iddef_promo_code = fields.Integer(dump_only=True)
    name = fields.String(required=True,validate=validate.Length(max=150))
    code = fields.String(required=True,validate=validate.Length(max=50))
    #iddef_property = fields.Integer(required=True)
    iddef_promo_code_discount_type = fields.Integer(required=True)
    value_discount = fields.Float(required=True)
    iddef_promo_code_type_amount = fields.Integer(required=True)
    currency_code = fields.String(required=True,validate=validate.Length(max=15))
    room_types_option = fields.Integer(required=True,validate=validate.Length(max=6))
    min_LOS_option = fields.Integer(required=True,validate=validate.Length(max=6))
    min_LOS_value = fields.Float(required=True)
    min_booking_amount_option = fields.Integer(required=True,validate=validate.Length(max=6))
    min_booking_value = fields.Float(required=True)
    max_booking_amount_option = fields.Integer(required=True,validate=validate.Length(max=6))
    max_booking_value = fields.Float(required=True)
    stay_dates_option = fields.Integer(required=True,validate=validate.Length(max=6))
    stay_dates = fields.Dict(required=True)
    booking_dates_option =fields.Integer(required=True,validate=validate.Length(max=6))
    booking_dates = fields.Dict(required=True)
    booking_times = fields.Dict(required=True)
    global_sales_limit_option = fields.Integer(required=True,validate=validate.Length(max=6))
    global_sales_limit_value = fields.Float(required=True)
    cancel_policy_id = fields.Integer(required=True,validate=validate.Length(max=11))
    channel_option = fields.Integer(required=True,validate=validate.Length(max=6))
    maximum_nights_option = fields.Integer(required=True, validate=validate.Length(max=6))
    maximum_nights_value = fields.Integer(required=True, validate=validate.Length(max=10))
    estado = fields.Integer()
    usuario_creacion = fields.String(required=True, validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")

class GetPromoCodeSchema(ma.Schema):
    iddef_promo_code = fields.Integer(dump_only=True)
    name = fields.String(required=True,validate=validate.Length(max=150))
    code = fields.String(required=True,validate=validate.Length(max=50))
    #iddef_property = fields.Integer(required=True)
    iddef_promo_code_discount_type = fields.Integer(required=True)
    value_discount = fields.Float(required=True)
    iddef_promo_code_type_amount = fields.Integer(required=True)
    currency_code = fields.String(required=True,validate=validate.Length(max=15))
    room_types_option = fields.Integer(required=True,validate=validate.Length(max=6))
    min_LOS_option = fields.Integer(required=True,validate=validate.Length(max=6))
    min_LOS_value = fields.Float(required=True)
    min_booking_amount_option = fields.Integer(required=True,validate=validate.Length(max=6))
    min_booking_value = fields.Float(required=True)
    max_booking_amount_option = fields.Integer(required=True,validate=validate.Length(max=6))
    max_booking_value = fields.Float(required=True)
    stay_dates_option = fields.Integer(required=True,validate=validate.Length(max=6))
    stay_dates = fields.Dict(required=True)
    booking_dates_option =fields.Integer(required=True,validate=validate.Length(max=6))
    booking_dates = fields.Dict(required=True)
    booking_times = fields.Dict(required=True)
    global_sales_limit_option = fields.Integer(required=True,validate=validate.Length(max=6))
    global_sales_limit_value = fields.Float(required=True)
    cancel_policy_id = fields.Integer(required=True,validate=validate.Length(max=11))
    channel_option = fields.Integer(required=True,validate=validate.Length(max=6))
    maximum_nights_option = fields.Integer(required=True, validate=validate.Length(max=6))
    maximum_nights_value = fields.Integer(required=True, validate=validate.Length(max=10))
    estado = fields.Integer()
    usuario_creacion = fields.String(required=True, validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    market_option = fields.Integer()
    market_targeting = fields.List(fields.Integer())
    rooms_rateplan = fields.List(fields.String())

class PromoCodePostPutSchema(ma.Schema):
    iddef_promo_code = fields.Integer(dump_only=False)
    #iddef_property = fields.Integer(required=True)
    name = fields.String(required=True,validate=validate.Length(max=150))
    code = fields.String(required=True,validate=validate.Length(max=50))
    iddef_promo_code_discount_type = fields.Integer()
    value_discount = fields.Float(required=True)
    iddef_promo_code_type_amount = fields.Integer()
    currency_code = fields.String(validate=validate.Length(max=15))
    room_types_option = fields.Integer()
    maximum_nights_option = fields.Integer()
    maximum_nights_value = fields.Integer()
    min_LOS_option = fields.Integer()
    min_LOS_value = fields.Float()
    min_booking_amount_option = fields.Integer()
    min_booking_value = fields.Float()
    max_booking_amount_option = fields.Integer()
    max_booking_value = fields.Float()
    stay_dates_option = fields.Integer()
    stay_dates_value = fields.List(fields.Dict())
    booking_dates_option = fields.Integer()
    booking_dates_value = fields.List(fields.Dict())
    booking_times_value = fields.List(fields.Dict())
    global_sales_limit_option = fields.Integer()
    global_sales_limit_value = fields.Float()
    channel_option = fields.Integer()
    cancel_policy_id =  fields.Integer()
    description = fields.List(fields.Dict())
    channel_list = fields.List(fields.Dict())
    country_option = fields.Integer(required=True)
    country_targeting = fields.List(fields.String())
    market_option = fields.Integer(required=True)
    market_targeting = fields.List(fields.Integer())
    promo_code_rateplans = fields.List(fields.Dict(),required=True)
    estado = fields.Integer()
    usuario_creacion = fields.String(required=True, validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")

class GetInternalPromoCodeSchema(ma.Schema):
    property_code = fields.String(required=True, validate=validate.Length(max=6))
    date_start = fields.DateTime("%Y-%m-%d", required=True)
    date_end = fields.DateTime("%Y-%m-%d", required=True)
    rateplans = fields.List(fields.Integer(), required=True)
    rooms = fields.List(fields.Integer(), required=True)
    market = fields.String(validate=validate.Length(max=15))
    country = fields.String(validate=validate.Length(max=45))
    lang_code = fields.String(validate=validate.Length(max=10))
    booking_amount = fields.Float()