from datetime import datetime

from config import db, ma
from marshmallow import Schema, fields, validate
from models.property import Property
from models.amenity import Amenity, AmenitySchema, GetIdAmenitySchema, RoomAmenity
from models.text_lang import TextLang, TextLangSchema, GetTextLangSchema
from models.area_unit import AreaUnit, AreaUnitSchema
from models.media import Media, MediaSchema, publicGetListMedia
from common.util import Util

class RoomTypeCategory(db.Model):
    __tablename__="def_room_type_category"
    __table_args__ = {'extend_existing': True} 

    iddef_room_type_category = db.Column(db.Integer,primary_key=True)
    iddef_property = db.Column(db.Integer,db.ForeignKey("def_property.iddef_property"), nullable=False)
    room_description = db.Column(db.String(150),default="")
    room_code = db.Column(db.String(10))
    room_code_opera = db.Column(db.String(10))
    max_adt = db.Column(db.Integer,nullable=False)
    max_chd = db.Column(db.Integer,nullable=False)
    acept_chd = db.Column(db.Integer,nullable=False)
    single_parent_policy = db.Column(db.Integer,default=2)
    smoking = db.Column(db.Integer,nullable=False)
    min_adt= db.Column(db.Integer,nullable=False)
    min_chd= db.Column(db.Integer,nullable=False)
    standar_ocupancy= db.Column(db.Integer, nullable=False)
    max_ocupancy_pms = db.Column(db.Integer,nullable=False)
    is_room_of_house = db.Column(db.Integer,nullable=False)
    area = db.Column(db.Integer)
    area_unit = db.Column(db.Integer, db.ForeignKey("def_area_unit.iddef_area_unit"), nullable=False)
    max_ocupancy = db.Column(db.Integer,nullable=False)
    min_ocupancy = db.Column(db.Integer,nullable=False)
    room_order = db.Column(db.Integer,nullable=False)
    market_option = db.Column(db.Integer,nullable=False)
    market_targeting = db.Column(db.JSON, nullable=False)
    estado = db.Column(db.Integer,nullable=False)
    usuario_creacion = db.Column(db.String(45), nullable=False, default="")
    fecha_creacion = db.Column(db.DateTime, default=datetime.utcnow)
    usuario_ultima_modificacion = db.Column(db.String(45), default="")
    fecha_ultima_modificacion = db.Column(
        db.DateTime, default="1900-01-01 00:00:00", onupdate=datetime.utcnow)
    area_code = db.relationship('AreaUnit', backref=db.backref('def_room_type_category', lazy='dynamic'))

class RoomTypeCategorySchemaLangs(ma.Schema):
    iddef_room_type_category = fields.Integer()
    iddef_property = fields.Integer(required=True)
    room_code = fields.String(required=True,validate=validate.Length(max=10))
    room_description = fields.List(fields.Nested(GetTextLangSchema),dump_only=True)
    description = fields.List(fields.Nested(GetTextLangSchema),dump_only=True)
    max_adt = fields.Integer(required=True)
    max_chd = fields.Integer(required=True)
    acept_chd = fields.Integer(required=True)
    single_parent_policy = fields.Integer()
    smoking = fields.Integer(required=True)
    room_code_opera = fields.String(dump_only=True)
    min_adt = fields.Integer(required=True)
    min_chd = fields.Integer(required=True)
    standar_ocupancy = fields.Integer(required=True)
    area = fields.Integer(required=True)
    area_unit = fields.Integer(required=True)
    max_ocupancy = fields.Integer(required=True)
    min_ocupancy = fields.Integer(required=True)
    room_order = fields.Integer(required=True)
    market_option = fields.String(validate=validate.Length(max=4))
    market_targeting = fields.List(fields.String())
    estado = fields.Integer()
    usuario_creacion = fields.String(required=True,validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(required=True, validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")

class RoomDetailRqSchema(ma.Schema):
    iddef_room_type_category = fields.Integer(dump_only=True)
    iddef_property = fields.Integer(dump_only=True)
    room_code = fields.String(dump_only=True)
    room_description = fields.String(dump_only=True)
    max_adt = fields.Integer(dump_only=True)
    max_chd = fields.Integer(dump_only=True)
    acept_chd = fields.Integer(dump_only=True)
    single_parent_policy = fields.Integer(dump_only=True)
    smoking = fields.Integer(dump_only=True)
    min_adt = fields.Integer(dump_only=True)
    min_chd = fields.Integer(dump_only=True)
    standar_ocupancy = fields.Integer(dump_only=True)
    area = fields.Float(dump_only=True)
    area_code = ma.Pluck("AreaUnitSchema", 'unit_code',dump_only=True)
    max_ocupancy = fields.Integer(dump_only=True)
    min_ocupancy = fields.Integer(dump_only=True)
    room_order = fields.Integer(dump_only=True)
    room_media = fields.List(fields.Nested(publicGetListMedia))
    room_amenities = fields.List(fields.Nested(RoomAmenity))
    estado = fields.Integer(dump_only=True)

class PublicRoomsDetailsRq(ma.Schema):
    lang_code = fields.String(load_only=True,required=True)
    market = fields.String(load_only=True,required=True)
    property_code = fields.String(load_only=True,required=True)
    date_start = fields.Date(load_only=True,required=True)
    date_end = fields.Date(load_only=True,required=True)
    pax = fields.Dict(fields.String(),fields.Integer(),load_only=True)
    rooms = fields.List(fields.Integer(),load_only=True)
    roomtype = fields.String(load_only=True)

    property_media = fields.List(fields.Nested(publicGetListMedia),dump_only=True)
    rooms_detail = fields.List(fields.Dict(),dump_only=True)

class RoomTypeCategorySchema(ma.Schema):
    iddef_room_type_category = fields.Integer()
    iddef_property = fields.Integer(required=True)
    room_code = fields.String(required=True,validate=validate.Length(max=10))
    room_description = fields.String(required=True,validate=validate.Length(max=150))
    max_adt = fields.Integer(required=True)
    max_chd = fields.Integer(required=True)
    acept_chd = fields.Integer(required=True)
    single_parent_policy = fields.Integer()
    smoking = fields.Integer(required=True)
    min_adt = fields.Integer(required=True)
    min_chd = fields.Integer(required=True)
    standar_ocupancy = fields.Integer(required=True)
    area = fields.Integer(required=True)
    area_unit = fields.Integer(required=True)
    max_ocupancy = fields.Integer(required=True)
    min_ocupancy = fields.Integer(required=True)
    room_order = fields.Integer(required=True)
    market_option = fields.String(validate=validate.Length(max=4),dump_only=True)
    market_targeting = fields.List(fields.String(), dump_only=True)
    estado = fields.Integer()
    usuario_creacion = fields.String(required=True,validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(required=True, validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")

class RoomTypeCategoryToSelect(ma.Schema):
    iddef_room_type_category = fields.Integer()
    iddef_property = fields.Integer(required=True)
    room_code = fields.String(required=True,validate=validate.Length(max=10))
    room_name = fields.List(fields.Nested(GetTextLangSchema),dump_only=True)
    estado = fields.Integer()
    usuario_creacion = fields.String(required=True,validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(required=True, validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")

class GetRoomTypeCategorySchema(ma.Schema):
    iddef_room_type_category = fields.Integer(dump_only=True)
    iddef_property = fields.Integer()
    room_code = fields.String(validate=validate.Length(max=10),allow_none=False)
    room_description = fields.String(validate=validate.Length(max=150))
    max_adt = fields.Integer()
    max_chd = fields.Integer()
    acept_chd = fields.Integer()
    single_parent_policy = fields.Integer()
    estado = fields.Integer()
    usuario_creacion = fields.String(validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(required=True, validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")

class CreateRoomtypeSchema(ma.Schema):
    iddef_room_type_category = fields.Integer(dump_only=True)
    iddef_property = fields.Integer(required=True)
    area = fields.Integer()
    smoking = fields.Integer()
    room_code = fields.String(validate=validate.Length(max=10),required=True)
    max_adt = fields.Integer(required=True)
    max_chd = fields.Integer(required=True)
    min_adt = fields.Integer(required=True)
    min_chd = fields.Integer(required=True)
    acept_chd = fields.Integer()
    single_parent_policy = fields.Integer()
    estado = fields.Integer()
    standar_ocupancy = fields.Integer(required=True)
    area_unit = fields.Integer(required=True)
    max_ocupancy = fields.Integer(required=True)
    min_ocupancy = fields.Integer(required=True)
    room_order = fields.Integer(required=True)
    market_option = fields.String(validate=validate.Length(max=4),required=True)
    market_targeting = fields.List(fields.String(), required=True)
    description = fields.List(fields.Nested(GetTextLangSchema),required=True)
    names = fields.List(fields.Nested(GetTextLangSchema),required=True)
    amenities = fields.List(fields.Nested(GetIdAmenitySchema),required=True)

class GetRoomTypeCategoryListSchema(ma.Schema):
    room_code = fields.String(validate=validate.Length(max=10))
    room_name = fields.String(validate=validate.Length(max=350))

class GetRoomTypeCategoryPropertySchema(ma.Schema):
    iddef_room_type_category = fields.Integer()
    iddef_property = fields.Integer()
    room_code = fields.String(validate=validate.Length(max=10))
    room_description = fields.String(validate=validate.Length(max=150))
    max_adt = fields.Integer()
    max_chd = fields.Integer()
    acept_chd = fields.Integer()
    single_parent_policy = fields.Integer()
    smoking = fields.Integer()
    min_adt = fields.Integer()
    min_chd = fields.Integer()
    standar_ocupancy = fields.Integer()
    area = fields.Integer()
    area_unit = fields.Integer()
    area_code = fields.Nested(AreaUnitSchema, exclude=Util.get_default_excludes())
    max_ocupancy = fields.Integer()
    min_ocupancy = fields.Integer()
    room_order = fields.Integer()
    estado = fields.Integer()
    usuario_creacion = fields.String(validate=validate.Length(max=45))
    fecha_creacion = fields.DateTime("%Y-%m-%d %H:%M:%S")
    usuario_ultima_modificacion = fields.String(validate=validate.Length(max=45))
    fecha_ultima_modificacion = fields.DateTime("%Y-%m-%d %H:%M:%S")

class RoomTypeCategoryRoomCodeSchema(ma.Schema):
    id_property = fields.Integer()
    room_code = fields.String(validate=validate.Length(max=10))
    adults = fields.Integer()
    childs = fields.Integer()
